project_id = "zwloyqcwyfkimwkohpnd"

[functions.delete-user]
verify_jwt = false

[functions.pluuug-api]
verify_jwt = false

[functions.generate-quote-pdf]
verify_jwt = false

[functions.pluuug-sync-colors]
verify_jwt = false

[functions.pluuug-reverse-sync]
verify_jwt = false
