project_id = "zwloyqcwyfkimwkohpnd"

[functions.delete-user]
verify_jwt = false

[functions.pluuug-api]
verify_jwt = false

[functions.generate-quote-pdf]
verify_jwt = false

[functions.pluuug-sync-colors]
verify_jwt = false

[functions.pluuug-reverse-sync]
verify_jwt = false

[functions.pluuug-bulk-resync]
verify_jwt = false

[functions.admin-update-user]
verify_jwt = false

[functions.password-reset]
verify_jwt = false

[functions.notion-projects]
verify_jwt = false

[functions.leave-promotion-check]
verify_jwt = false
