substitutions:
  _IMAGE_URI: asia-northeast3-docker.pkg.dev/$PROJECT_ID/acbank-workers/acbank-quote-wizard-worker:latest

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - workers/quote-wizard-worker/Dockerfile
      - -t
      - ${_IMAGE_URI}
      - .

images:
  - ${_IMAGE_URI}
