import type { JSONContent } from '@tiptap/react';

const paragraph = (text: string): JSONContent => ({
  type: 'paragraph',
  content: text ? [{ type: 'text', text }] : undefined,
});

const heading = (text: string, level: number): JSONContent => ({
  type: 'heading',
  attrs: { level },
  content: [{ type: 'text', text }],
});

const bold = (text: string): JSONContent => ({
  type: 'text',
  text,
  marks: [{ type: 'bold' }],
});

const boldParagraph = (text: string): JSONContent => ({
  type: 'paragraph',
  content: [bold(text)],
});

export interface PrebuiltTemplate {
  id: string;
  name: string;
  type: 'labor' | 'salary';
  content: JSONContent;
}

export const PREBUILT_TEMPLATES: PrebuiltTemplate[] = [
  {
    id: 'labor-regular',
    name: '근로계약서 (정규직 통상임금)',
    type: 'labor',
    content: {
      type: 'doc',
      content: [
        { type: 'heading', attrs: { level: 1, textAlign: 'center' }, content: [bold('근 로 계 약 서')] },
        paragraph(''),
        paragraph('{{회사명}} (이하 "사업주"라 한다)과 {{구성원이름}} (이하 "근로자"라 한다)은 다음과 같이 근로계약을 체결한다.'),
        paragraph(''),
        boldParagraph('제1조 (근로계약기간)'),
        paragraph('근로계약기간은 {{계약시작일}} 부터 {{계약종료일}} 까지로 한다.'),
        paragraph(''),
        boldParagraph('제2조 (근무장소)'),
        paragraph('근무장소: {{회사주소}}'),
        paragraph(''),
        boldParagraph('제3조 (업무내용)'),
        paragraph('{{구성원이름}}은(는) {{직위}} 직위로서 소속 부서({{부서}})의 업무를 수행한다.'),
        paragraph(''),
        boldParagraph('제4조 (근로시간)'),
        paragraph('근무형태: {{근무형태}}'),
        paragraph('근무요일: {{근무요일}}'),
        paragraph('시업시각: 09:00 / 종업시각: 18:00 (휴게시간 12:00~13:00)'),
        paragraph(''),
        boldParagraph('제5조 (임금)'),
        paragraph('연봉: {{연봉}}원'),
        paragraph('월급: {{월급}}원'),
        paragraph('기본급: {{기본급}}원'),
        paragraph('임금은 매월 {{급여일}}일에 근로자 명의의 예금통장에 입금하여 지급한다.'),
        paragraph(''),
        boldParagraph('제6조 (수습기간)'),
        paragraph('수습기간: {{수습기간}}'),
        paragraph('수습기간: {{수습시작일}} ~ {{수습종료일}}'),
        paragraph(''),
        boldParagraph('제7조 (연차유급휴가)'),
        paragraph('연차유급휴가는 근로기준법에서 정하는 바에 따라 부여한다.'),
        paragraph(''),
        boldParagraph('제8조 (기타)'),
        paragraph('본 계약에 명시되지 않은 사항은 근로기준법 및 관계법령에 따른다.'),
        paragraph(''),
        paragraph(''),
        { type: 'paragraph', attrs: { textAlign: 'center' }, content: [{ type: 'text', text: '{{계약일}}' }] },
        paragraph(''),
        paragraph('(사업주) {{회사명}}  대표이사 {{대표자명}}  (인)'),
        paragraph('(근로자) {{구성원이름}}  (인)'),
      ],
    },
  },
  {
    id: 'labor-comprehensive',
    name: '근로계약서 (정규직 포괄임금)',
    type: 'labor',
    content: {
      type: 'doc',
      content: [
        { type: 'heading', attrs: { level: 1, textAlign: 'center' }, content: [bold('근 로 계 약 서')] },
        paragraph(''),
        paragraph('{{회사명}} (이하 "사업주"라 한다)과 {{구성원이름}} (이하 "근로자"라 한다)은 다음과 같이 근로계약을 체결한다.'),
        paragraph(''),
        boldParagraph('제1조 (근로계약기간)'),
        paragraph('근로계약기간은 {{계약시작일}} 부터 {{계약종료일}} 까지로 한다.'),
        paragraph(''),
        boldParagraph('제2조 (근무장소 및 업무)'),
        paragraph('근무장소: {{회사주소}}'),
        paragraph('{{구성원이름}}은(는) {{직위}} 직위로서 소속 부서({{부서}})의 업무를 수행한다.'),
        paragraph(''),
        boldParagraph('제3조 (근로시간)'),
        paragraph('근무형태: {{근무형태}}'),
        paragraph('근무요일: {{근무요일}}'),
        paragraph(''),
        boldParagraph('제4조 (임금 - 포괄임금제)'),
        paragraph('연봉: {{연봉}}원'),
        paragraph('월급: {{월급}}원'),
        paragraph('- 기본급: {{기본급}}원'),
        paragraph('- 고정연장근로수당 ({{고정연장시간}}시간): {{고정연장수당}}원'),
        paragraph('임금은 매월 {{급여일}}일에 지급한다.'),
        paragraph(''),
        boldParagraph('제5조 (수습기간)'),
        paragraph('수습기간: {{수습기간}} ({{수습시작일}} ~ {{수습종료일}})'),
        paragraph(''),
        boldParagraph('제6조 (기타)'),
        paragraph('본 계약에 명시되지 않은 사항은 근로기준법 및 관계법령에 따른다.'),
        paragraph(''),
        paragraph(''),
        { type: 'paragraph', attrs: { textAlign: 'center' }, content: [{ type: 'text', text: '{{계약일}}' }] },
        paragraph(''),
        paragraph('(사업주) {{회사명}}  대표이사 {{대표자명}}  (인)'),
        paragraph('(근로자) {{구성원이름}}  (인)'),
      ],
    },
  },
  {
    id: 'salary-annual',
    name: '연봉계약서',
    type: 'salary',
    content: {
      type: 'doc',
      content: [
        { type: 'heading', attrs: { level: 1, textAlign: 'center' }, content: [bold('연 봉 계 약 서')] },
        paragraph(''),
        paragraph('{{회사명}} (이하 "회사"라 한다)과 {{구성원이름}} (이하 "직원"이라 한다)은 다음과 같이 연봉계약을 체결한다.'),
        paragraph(''),
        boldParagraph('제1조 (계약기간)'),
        paragraph('본 연봉계약의 적용기간은 {{계약시작일}} 부터 {{계약종료일}} 까지로 한다.'),
        paragraph(''),
        boldParagraph('제2조 (연봉)'),
        paragraph('직원의 연봉은 금 {{연봉}}원 (월 {{월급}}원)으로 정한다.'),
        paragraph(''),
        boldParagraph('제3조 (임금 구성)'),
        paragraph('- 기본급: {{기본급}}원'),
        paragraph('- 고정연장근로수당 ({{고정연장시간}}시간 분): {{고정연장수당}}원'),
        paragraph(''),
        boldParagraph('제4조 (지급방법)'),
        paragraph('연봉은 12개월로 균등 분할하여 매월 {{급여일}}일에 지급한다.'),
        paragraph(''),
        boldParagraph('제5조 (기타)'),
        paragraph('본 계약에 명시되지 않은 사항은 회사 규정 및 관계법령에 따른다.'),
        paragraph(''),
        paragraph(''),
        { type: 'paragraph', attrs: { textAlign: 'center' }, content: [{ type: 'text', text: '{{계약일}}' }] },
        paragraph(''),
        paragraph('(회사) {{회사명}}  대표이사 {{대표자명}}  (인)'),
        paragraph('(직원) {{구성원이름}}  (인)'),
      ],
    },
  },
  {
    id: 'nda',
    name: '비밀 유지 서약서',
    type: 'labor',
    content: {
      type: 'doc',
      content: [
        { type: 'heading', attrs: { level: 1, textAlign: 'center' }, content: [bold('비 밀 유 지 서 약 서')] },
        paragraph(''),
        paragraph('본인 {{구성원이름}}은(는) {{회사명}}(이하 "회사")에 입사함에 있어 다음 사항을 서약합니다.'),
        paragraph(''),
        boldParagraph('제1조 (비밀유지 의무)'),
        paragraph('본인은 재직 중 또는 퇴직 후에도 업무상 알게 된 회사의 경영, 영업, 기술상의 비밀 및 고객정보를 제3자에게 누설하거나 외부에 공개하지 않겠습니다.'),
        paragraph(''),
        boldParagraph('제2조 (자료 반납)'),
        paragraph('본인은 퇴직 시 회사의 모든 자료, 문서, 전자데이터 등을 즉시 반납하겠습니다.'),
        paragraph(''),
        boldParagraph('제3조 (손해배상)'),
        paragraph('위 서약 사항을 위반하여 회사에 손해를 끼친 경우 민·형사상의 책임을 지겠습니다.'),
        paragraph(''),
        paragraph(''),
        { type: 'paragraph', attrs: { textAlign: 'center' }, content: [{ type: 'text', text: '{{계약일}}' }] },
        paragraph(''),
        paragraph('서약인: {{구성원이름}}  (인)'),
        paragraph('소속: {{부서}}'),
        paragraph('직위: {{직위}}'),
      ],
    },
  },
  {
    id: 'non-compete',
    name: '경업 금지 서약서',
    type: 'labor',
    content: {
      type: 'doc',
      content: [
        { type: 'heading', attrs: { level: 1, textAlign: 'center' }, content: [bold('경 업 금 지 서 약 서')] },
        paragraph(''),
        paragraph('본인 {{구성원이름}}은(는) {{회사명}}(이하 "회사") 퇴직 후 다음 사항을 준수할 것을 서약합니다.'),
        paragraph(''),
        boldParagraph('제1조 (경업금지 범위)'),
        paragraph('본인은 퇴직일로부터 1년간 회사와 동종 또는 유사한 업종에 취업하거나 사업을 영위하지 않겠습니다.'),
        paragraph(''),
        boldParagraph('제2조 (위반 시 조치)'),
        paragraph('위 서약 사항을 위반한 경우 회사가 입은 손해에 대해 배상하겠습니다.'),
        paragraph(''),
        paragraph(''),
        { type: 'paragraph', attrs: { textAlign: 'center' }, content: [{ type: 'text', text: '{{계약일}}' }] },
        paragraph(''),
        paragraph('서약인: {{구성원이름}}  (인)'),
      ],
    },
  },
  {
    id: 'privacy-consent',
    name: '개인 정보 이용 동의서',
    type: 'labor',
    content: {
      type: 'doc',
      content: [
        { type: 'heading', attrs: { level: 1, textAlign: 'center' }, content: [bold('개인정보 수집·이용 동의서')] },
        paragraph(''),
        paragraph('{{회사명}}(이하 "회사")은 다음과 같이 개인정보를 수집·이용하고자 합니다.'),
        paragraph(''),
        boldParagraph('1. 수집 항목'),
        paragraph('성명, 생년월일, 연락처, 주소, 학력, 경력사항, 가족관계 등'),
        paragraph(''),
        boldParagraph('2. 수집·이용 목적'),
        paragraph('인사관리, 급여관리, 4대보험 가입, 연말정산 등'),
        paragraph(''),
        boldParagraph('3. 보유 및 이용 기간'),
        paragraph('고용관계 종료 시까지 (단, 관계법령에 따라 보존이 필요한 경우 해당 기간까지)'),
        paragraph(''),
        paragraph('본인은 위 내용을 충분히 이해하였으며, 개인정보 수집·이용에 동의합니다.'),
        paragraph(''),
        { type: 'paragraph', attrs: { textAlign: 'center' }, content: [{ type: 'text', text: '{{계약일}}' }] },
        paragraph(''),
        paragraph('동의인: {{구성원이름}}  (인)'),
      ],
    },
  },
];
